### ISSUE TITLE
[PkgEval] CRF may have a testing issue on Julia 0.3 (2014-05-24)

### ISSUE THREAD

**Issue by IainNZ** [slyrz/CRF.jl#2]
[PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) is a script that runs nightly. It attempts to load all Julia packages and run their tests (if available) on both the stable version of Julia (0.2) and the nightly build of the unstable version (0.3). The results of this script are used to generate a [package listing](http://iainnz.github.io/packages.julialang.org/) enhanced with testing results.
#### On Julia 0.3
- On **2014-05-23** the testing status was `No tests, but package loads.`.
- On **2014-05-24** the testing status changed to `Tests fail, but package loads.`.

`Tests fail, but package loads.` means that PackageEvaluator found the tests for your package, executed them, and they didn't pass. However, trying to load your package with `using` worked.

`No tests, but package loads.` means that PackageEvaluator did not find tests for your package. However, trying to load your package with `using` worked.

_This issue was filed because your testing status became worse. No additional issues will be filed if your package remains in this state, and no issue will be filed if it improves. If you'd like to opt-out of these status-change messages, reply to this message saying you'd like to and @IainNZ will add an exception. If you'd like to discuss [PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) please file an issue at the repository. For example, your package may be untestable on the test machine due to a dependency - an exception can be added._

**Comment by IainNZ** [comment]
```
INFO: Installing CRF v0.1.0
INFO: Package database updated
ERROR: no method feature_vector(Bool, Bool, Array{Array{Float64,1},1}, Int64)
 in #s1 at /home/idunning/pkgtest/.julia/v0.3/CRF/src/base.jl:59
 in Sequence at /home/idunning/pkgtest/.julia/v0.3/CRF/src/base.jl:81
 in include at boot.jl:244
 in anonymous at no file:11
 in include at boot.jl:244
 in include_from_node1 at loading.jl:128
while loading /home/idunning/pkgtest/.julia/v0.3/CRF/test/base.jl, in expression starting on line 32
while loading /home/idunning/pkgtest/.julia/v0.3/CRF/test/runtests.jl, in expression starting on line 9
INFO: Package database updated
```

**Comment by slyrz** [comment]
[PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) status:

```
CRF changed to 'Tests pass.' from 'Tests fail, but package loads.'
```

Everything fine now.
